image bg subway fog = "images/bg/subway-fog.jpg"
image bg past day = "images/bg/fantasy-forest-day.png"
image bg past night = "images/bg/fantasy-forest-night.png"
image bg future space = "images/bg/future-space.png"
image bg future med bay = "images/bg/future-med-station.jpg"
